<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Views\Shared\ViewBoxError.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlienFruit.Astra\AlienFruit.Astra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Views\Shared\ViewBoxError.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="6.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
