<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Middlewares\**" />
    <EmbeddedResource Remove="Middlewares\**" />
    <None Remove="Middlewares\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Core\Resources\load-check.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Core\Resources\load-check.js" />
    <EmbeddedResource Include="ViewBoxLink\Resources\viewboxlink-init-script.template.js" />
    <EmbeddedResource Include="ViewBox\Resources\viewbox-init-script.template.js" />
    <EmbeddedResource Include="ViewBox\Resources\viewbox.js" />
  </ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Html.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.3.0" />
    <PackageReference Include="NUglify" Version="1.21.17" />
    <PackageReference Include="Scriban" Version="6.5.2" />
  </ItemGroup>

</Project>