<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

<!-- NuGet Package Properties -->
    <PackageId>AlienFruit.Astra</PackageId>
    <Title>AlienFruit.Astra - Dynamic Content Loading for ASP.NET MVC</Title>
    <GitVersion_NoFetchEnabled>true</GitVersion_NoFetchEnabled>
    <Authors>Alexander Prokopovich</Authors>
    <Company>AlienFruit</Company>
    <Description>A library that allows dynamic content loading in .NET MVC applications and enables smooth navigation between website pages without refreshing the entire page in the browser.</Description>
    <PackageTags>asp-net-core;mvc;dynamic-content;ajax;navigation;javascript;css</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/alienfruit/AlienFruit.Astra</PackageProjectUrl>
    <RepositoryUrl>https://github.com/alienfruit/AlienFruit.Astra</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Copyright>Copyright © AlienFruit 2025</Copyright>
    <LangVersion>latest</LangVersion>
    <PackageIcon>logo-icon-github.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AlienFruit.Astra.Tests" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Middlewares\**" />
    <EmbeddedResource Remove="Middlewares\**" />
    <None Remove="Middlewares\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Core\Resources\load-check.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Core\Resources\load-check.js" />
    <EmbeddedResource Include="ViewBoxLinkGroup\Resources\viewboxlink-group-init-script.template.js" />
    <EmbeddedResource Include="ViewBoxLink\Resources\viewboxlink-init-script.template.js" />
    <EmbeddedResource Include="ViewBox\Resources\viewbox-init-script.template.js" />
    <EmbeddedResource Include="ViewBox\Resources\viewbox.js" />
    <EmbeddedResource Include="ViewBox\Resources\ViewBoxError.html" />
  </ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="..\..\design\logo-icon-github.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>
<ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="6.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUglify" Version="1.21.17" />
    <PackageReference Include="Scriban" Version="7.0.6" />
  </ItemGroup>
	<ItemGroup>
	  <None Update="README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>